# 基本

In [1]:
import torch

In [2]:
print(torch.__version__)

1.2.0


In [4]:
x=torch.empty(5,3)
print(x)

tensor([[-3.3416e-25,  4.5769e-41, -7.4492e+30],
        [ 4.5769e-41, -3.3165e-25,  4.5769e-41],
        [-7.4486e+30,  4.5769e-41, -3.3165e-25],
        [ 4.5769e-41, -7.4485e+30,  4.5769e-41],
        [-3.3416e-25,  4.5769e-41, -7.4599e+30]])


In [5]:
x=torch.rand(5,3)
print(x)

tensor([[0.9394, 0.7662, 0.0326],
        [0.5301, 0.6246, 0.3125],
        [0.7963, 0.9134, 0.4860],
        [0.1567, 0.8721, 0.6872],
        [0.4826, 0.0700, 0.6116]])


In [7]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x=x.new_ones(5,3,dtype=torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [10]:
x=torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[ 0.8542,  1.8867,  0.3242],
        [-1.4771, -0.2210,  1.7040],
        [-0.9205,  2.0000, -1.1075],
        [-2.3680, -0.1033,  0.0197],
        [-0.6237,  0.7709, -0.4485]])


In [11]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [12]:
x=torch.arange(1,20,3)
print(x)

tensor([ 1,  4,  7, 10, 13, 16, 19])


In [13]:
x=torch.linspace(1,20,3)
print(x)

tensor([ 1.0000, 10.5000, 20.0000])


In [14]:
x=torch.eye(6,4)
print(x)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


# 基本操作

In [17]:
x=torch.rand(5,3)
y=torch.rand(5,3)
print(x+y)

tensor([[0.5804, 0.4504, 0.1968],
        [0.8410, 0.4832, 1.6445],
        [0.4282, 0.7375, 1.1855],
        [0.0931, 0.3911, 1.3047],
        [1.6347, 0.9819, 1.2608]])


In [18]:
print(torch.add(x,y))

tensor([[0.5804, 0.4504, 0.1968],
        [0.8410, 0.4832, 1.6445],
        [0.4282, 0.7375, 1.1855],
        [0.0931, 0.3911, 1.3047],
        [1.6347, 0.9819, 1.2608]])


In [19]:
y.add_(x)
print(y)

tensor([[0.5804, 0.4504, 0.1968],
        [0.8410, 0.4832, 1.6445],
        [0.4282, 0.7375, 1.1855],
        [0.0931, 0.3911, 1.3047],
        [1.6347, 0.9819, 1.2608]])


In [20]:
y=x[0,:]
y+=1
print(y)
print(x[0,:])

tensor([1.5170, 1.1261, 1.0311])
tensor([1.5170, 1.1261, 1.0311])


In [24]:
y=x.view(15)
z=x.view(-1,5)
print(x.shape,y.shape,z.shape)

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [25]:
x+=1
print(x)
print(y)

tensor([[2.5170, 2.1261, 2.0311],
        [1.6576, 1.3743, 1.6516],
        [1.0555, 1.2587, 1.3961],
        [1.0163, 1.0394, 1.6340],
        [1.7098, 1.0050, 1.3336]])
tensor([2.5170, 2.1261, 2.0311, 1.6576, 1.3743, 1.6516, 1.0555, 1.2587, 1.3961,
        1.0163, 1.0394, 1.6340, 1.7098, 1.0050, 1.3336])


In [26]:
x_cp=x.clone().view(15)
x-=1
print(x)
print(x_cp)

tensor([[1.5170, 1.1261, 1.0311],
        [0.6576, 0.3743, 0.6516],
        [0.0555, 0.2587, 0.3961],
        [0.0163, 0.0394, 0.6340],
        [0.7098, 0.0050, 0.3336]])
tensor([2.5170, 2.1261, 2.0311, 1.6576, 1.3743, 1.6516, 1.0555, 1.2587, 1.3961,
        1.0163, 1.0394, 1.6340, 1.7098, 1.0050, 1.3336])


In [27]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([2.8276])
2.827641487121582


In [29]:
x=torch.arange(1,3).view(1,2)
print(x)
y=torch.arange(1,4).view(3,1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [30]:
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_before=id(y)
y=y+x
print(id(y),id_before)

140284747456088 140284747456376


In [31]:
id_before=id(y)
y[:]=y+x
print(id(y)==id_before)

True


In [32]:
id_before=id(y)
torch.add(x,y,out=y)
print(id(y)==id_before)

True


In [33]:
a=torch.ones(5)
b=a.numpy()
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [34]:
a+=1
print(a,b)
b+=1
print(a,b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [35]:
import numpy as np

In [36]:
a=np.ones(5)
b=torch.from_numpy(a)
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [37]:
a+=1
print(a,b)
b+=1
print(a,b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [38]:
c=torch.tensor(a)
a+=1
print(a,c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [41]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu",torch.double))

tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)


In [42]:
!nvidia-smi

Fri Feb 28 17:59:02 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
| 23%   39C    P2    55W / 250W |    633MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:82:00.0 Off |                  N/A |
| 23%   35C    P8     9W / 250W |     10MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
        